### ISSUE TITLE
1.20.1 forge compatible

### ISSUE THREAD

**Issue by AlleCraft-alterego** [stfwi/anthillinside#4]
Now i test 1.20.1 neoforge version of mod on forge (1.4.18 of anthillinside) and work perfectly can be added forge tag to file on curseforge ?

**Comment by stfwi** [comment]
Hi, let me check that, should be not an issue....

**Comment by stfwi** [comment]
Yepp, could be edited on curse, no problem, check the curse client, it should show this version then: https://legacy.curseforge.com/minecraft/mc-mods/anthill-inside/files/4813437. Cheer's
